# Generated by Django 2.0.4 on 2018-05-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20180504_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
